### ISSUE TITLE
Set up Slack/IRC bridge

### ISSUE THREAD

**Issue by richbodo** [bugmark/bugmark#50]
Probably on linode with this:

https://github.com/aaronpk/Slack-IRC-Gateway

**Comment by richbodo** [comment]
#bugmark on irc.mozilla.org

**Comment by simransinghal** [comment]
@richbodo I want to work on this issue.

**Comment by simransinghal** [comment]
@andyl can I do this task or is it already done?

**Comment by snehasi** [comment]
@simransinghal This is already done.

**Comment by andyl** [comment]
It's done!  (see bugmark.slack.com)
